server:
  port: 8902

spring:
  application:
    name: Employee-service
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#logging:
#  pattern:
#    file:

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/